// This file was generated by schema-gen.
// DO NOT EDIT THIS FILE!

//! Generated 3D Tiles types.

#![allow(clippy::all)]

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// For `SCALAR` this is a number. For `STRING` this is a string. For `ENUM` this is a string that shall be a valid enum `name`, not an integer value. For `BOOLEAN` this is a boolean. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length array this is an array of `count` elements of the given `type`. For variable-length arrays this is an array of any length of the given `type`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AnyValue {
    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Metadata about the entire tileset.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Asset {
    /// Application-specific version of this tileset, e.g., for when an existing tileset is updated.
    #[serde(
        rename = "tilesetVersion",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub tileset_version: Option<String>,

    /// The 3D Tiles version. The version defines the JSON schema for the tileset JSON and the base set of tile formats.
    pub version: String,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A bounding volume that encloses a tile or its content. At least one bounding volume property is required. Bounding volumes include `box`, `region`, or `sphere`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct BoundingVolume {
    /// An array of 12 numbers that define an oriented bounding box. The first three elements define the x, y, and z values for the center of the box. The next three elements (with indices 3, 4, and 5) define the x axis direction and half-length. The next three elements (indices 6, 7, and 8) define the y axis direction and half-length. The last three elements (indices 9, 10, and 11) define the z axis direction and half-length.
    #[serde(rename = "box", skip_serializing_if = "Vec::is_empty", default)]
    pub r#box: Vec<f64>,

    /// An array of six numbers that define a bounding geographic region in EPSG:4979 coordinates with the order [west, south, east, north, minimum height, maximum height]. Longitudes and latitudes are in radians. The range for latitudes is [-PI/2,PI/2]. The range for longitudes is [-PI,PI]. The value that is given as the 'south' of the region shall not be larger than the value for the 'north' of the region. The heights are in meters above (or below) the WGS84 ellipsoid. The 'minimum height' shall not be larger than the 'maximum height'.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub region: Vec<f64>,

    /// An array of four numbers that define a bounding sphere. The first three elements define the x, y, and z values for the center of the sphere. The last element (with index 3) defines the radius in meters. The radius shall not be negative.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub sphere: Vec<f64>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A class containing a set of properties.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Class {
    /// The description of the class.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,

    /// The name of the class, e.g. for display purposes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// A dictionary, where each key is a property ID and each value is an object defining the property. Property IDs shall be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub properties: HashMap<String, ClassProperty>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A single property of a metadata class.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ClassProperty {
    /// Whether the property is an array. When `count` is defined the property is a fixed-length array. Otherwise the property is a variable-length array.
    #[serde(default)]
    pub array: bool,

    /// The datatype of the element's components. Required for `SCALAR`, `VECN`, and `MATN` types, and disallowed for other types.
    #[serde(
        rename = "componentType",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub component_type: Option<serde_json::Value>,

    /// The number of array elements. May only be defined when `array` is `true`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub count: Option<i64>,

    /// A default value to use when encountering a `noData` value or an omitted property. The value is given in its final form, taking the effect of `normalized`, `offset`, and `scale` properties into account. Shall not be defined if `required` is true.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub default: Option<AnyValue>,

    /// The description of the property.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,

    /// Enum ID as declared in the `enums` dictionary. Required when `type` is `ENUM`. Disallowed when `type` is not `ENUM`
    #[serde(rename = "enumType", skip_serializing_if = "Option::is_none", default)]
    pub enum_type: Option<String>,

    /// Maximum allowed value for the property. Only applicable to `SCALAR`, `VECN`, and `MATN` types. This is the maximum of all property values, after the transforms based on the `normalized`, `offset`, and `scale` properties have been applied. Not applicable to variable-length arrays.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub max: Option<NumericValue>,

    /// Minimum allowed value for the property. Only applicable to `SCALAR`, `VECN`, and `MATN` types. This is the minimum of all property values, after the transforms based on the `normalized`, `offset`, and `scale` properties have been applied. Not applicable to variable-length arrays.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub min: Option<NumericValue>,

    /// The name of the property, e.g. for display purposes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// A `noData` value represents missing data — also known as a sentinel value — wherever it appears. `BOOLEAN` properties may not specify `noData` values. This is given as the plain property value, without the transforms from the `normalized`, `offset`, and `scale` properties. Shall not be defined if `required` is true.
    #[serde(rename = "noData", skip_serializing_if = "Option::is_none", default)]
    pub no_data: Option<NoDataValue>,

    /// Specifies whether integer values are normalized. Only applicable to `SCALAR`, `VECN`, and `MATN` types with integer component types. For unsigned integer component types, values are normalized between `[0.0, 1.0]`. For signed integer component types, values are normalized between `[-1.0, 1.0]`. For all other component types, this property shall be false.
    #[serde(default)]
    pub normalized: bool,

    /// An offset to apply to property values. Only applicable to `SCALAR`, `VECN`, and `MATN` types when the component type is `FLOAT32` or `FLOAT64`, or when the property is `normalized`. Not applicable to variable-length arrays.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub offset: Option<NumericValue>,

    /// If required, the property shall be present in every entity conforming to the class. If not required, individual entities may include `noData` values, or the entire property may be omitted. As a result, `noData` has no effect on a required property. Client implementations may use required properties to make performance optimizations.
    #[serde(default)]
    pub required: bool,

    /// A scale to apply to property values. Only applicable to `SCALAR`, `VECN`, and `MATN` types when the component type is `FLOAT32` or `FLOAT64`, or when the property is `normalized`. Not applicable to variable-length arrays.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub scale: Option<NumericValue>,

    /// An identifier that describes how this property should be interpreted. The semantic cannot be used by other properties in the class.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub semantic: Option<String>,

    /// The element type.
    #[serde(rename = "type")]
    pub r#type: serde_json::Value,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Statistics about entities that conform to a class that was defined in a metadata schema.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ClassStatistics {
    /// The number of entities that conform to the class.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub count: Option<i64>,

    /// A dictionary, where each key corresponds to a property ID in the class' `properties` dictionary and each value is an object containing statistics about property values.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub properties: HashMap<String, PropertyStatistics>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Metadata about the tile's content and a link to the content.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Content {
    /// An optional bounding volume that tightly encloses tile content. tile.boundingVolume provides spatial coherence and tile.content.boundingVolume enables tight view frustum culling. When this is omitted, tile.boundingVolume is used.
    #[serde(
        rename = "boundingVolume",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub bounding_volume: Option<BoundingVolume>,

    /// The group this content belongs to. The value is an index into the array of `groups` that is defined for the containing tileset.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub group: Option<i64>,

    /// A uri that points to tile content. When the uri is relative, it is relative to the referring tileset JSON file.
    pub uri: String,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An object defining the values of an enum.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EnumDefinition {
    /// The description of the enum.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,

    /// The name of the enum, e.g. for display purposes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The type of the integer enum value.
    #[serde(rename = "valueType", default)]
    pub value_type: serde_json::Value,

    /// An array of enum values. Duplicate names or duplicate integer values are not allowed.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub values: Vec<EnumValue>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An enum value.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EnumValue {
    /// The description of the enum value.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,

    /// The name of the enum value.
    pub name: String,

    /// The integer enum value.
    pub value: i64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// 3D Tiles extension for S2 bounding volumes.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Extension3dTilesBoundingVolumeS2 {
    /// The maximum height of the tile, specified in meters above (or below) the WGS84 ellipsoid.
    #[serde(rename = "maximumHeight")]
    pub maximum_height: f64,

    /// The minimum height of the tile, specified in meters above (or below) the WGS84 ellipsoid.
    #[serde(rename = "minimumHeight")]
    pub minimum_height: f64,

    /// A hexadecimal representation of the S2CellId. Tokens shall be lower-case, shall not contain whitespace and shall have trailing zeros stripped.
    pub token: String,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl Extension3dTilesBoundingVolumeS2 {
    pub const EXTENSION_NAME: &str = "3DTILES_bounding_volume_S2";
}

/// 3DTILES_ellipsoid extension data to define the referenced ellipsoid
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Extension3dTilesEllipsoid {
    /// Name of the body the ellipsoid represents, or 'none'
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub body: Option<String>,

    /// An array of three numbers that define the X, Y and Z radii values in meters for the ellipsoid
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub radii: Vec<f64>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl Extension3dTilesEllipsoid {
    pub const EXTENSION_NAME: &str = "3DTILES_ellipsoid";
}

/// An object containing metadata about a group.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Group {
    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// This object allows a tile to be implicitly subdivided. Tile and content availability and metadata is stored in subtrees which are referenced externally.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ImplicitTiling {
    /// The numbers of the levels in the tree with available tiles.
    #[serde(rename = "availableLevels")]
    pub available_levels: i64,

    /// A string describing the subdivision scheme used within the tileset.
    #[serde(rename = "subdivisionScheme")]
    pub subdivision_scheme: serde_json::Value,

    /// The number of distinct levels in each subtree. For example, a quadtree with `subtreeLevels = 2` will have subtrees with 5 nodes (one root and 4 children).
    #[serde(rename = "subtreeLevels")]
    pub subtree_levels: i64,

    /// An object describing the location of subtree files.
    pub subtrees: Subtrees,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// For `SCALAR` this is a number. For `STRING` this is a string. For `ENUM` this is a string that shall be a valid enum `name`, not an integer value. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length arrays this is an array of `count` elements of the given `type`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct NoDataValue {
    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// For `SCALAR` this is a number. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length arrays this is an array of `count` elements of the given `type`.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct NumericValue {
    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A dictionary object of metadata about per-feature properties.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Properties {
    /// The maximum value of this property of all the features in the tileset. The maximum value shall not be smaller than the minimum value.
    pub maximum: f64,

    /// The minimum value of this property of all the features in the tileset. The maximum value shall not be smaller than the minimum value.
    pub minimum: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Statistics about property values.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PropertyStatistics {
    /// The maximum property value occurring in the tileset. Only applicable to `SCALAR`, `VECN`, and `MATN` types. This is the maximum of all property values, after the transforms based on the `normalized`, `offset`, and `scale` properties have been applied.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub max: Option<NumericValue>,

    /// The arithmetic mean of property values occurring in the tileset. Only applicable to `SCALAR`, `VECN`, and `MATN` types. This is the mean of all property values, after the transforms based on the `normalized`, `offset`, and `scale` properties have been applied.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub mean: Option<NumericValue>,

    /// The median of property values occurring in the tileset. Only applicable to `SCALAR`, `VECN`, and `MATN` types. This is the median of all property values, after the transforms based on the `normalized`, `offset`, and `scale` properties have been applied.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub median: Option<NumericValue>,

    /// The minimum property value occurring in the tileset. Only applicable to `SCALAR`, `VECN`, and `MATN` types. This is the minimum of all property values, after the transforms based on the `normalized`, `offset`, and `scale` properties have been applied.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub min: Option<NumericValue>,

    /// A dictionary, where each key corresponds to an enum `name` and each value is the number of occurrences of that enum. Only applicable when `type` is `ENUM`. For fixed-length arrays, this is an array of component-wise occurrences.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub occurrences: HashMap<String, serde_json::Value>,

    /// The standard deviation of property values occurring in the tileset. Only applicable to `SCALAR`, `VECN`, and `MATN` types. This is the standard deviation of all property values, after the transforms based on the `normalized`, `offset`, and `scale` properties have been applied.
    #[serde(
        rename = "standardDeviation",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub standard_deviation: Option<NumericValue>,

    /// The sum of property values occurring in the tileset. Only applicable to `SCALAR`, `VECN`, and `MATN` types. This is the sum of all property values, after the transforms based on the `normalized`, `offset`, and `scale` properties have been applied.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub sum: Option<NumericValue>,

    /// The variance of property values occurring in the tileset. Only applicable to `SCALAR`, `VECN`, and `MATN` types. This is the variance of all property values, after the transforms based on the `normalized`, `offset`, and `scale` properties have been applied.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub variance: Option<NumericValue>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An object defining classes and enums.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Schema {
    /// A dictionary, where each key is a class ID and each value is an object defining the class. Class IDs shall be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub classes: HashMap<String, Class>,

    /// The description of the schema.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,

    /// A dictionary, where each key is an enum ID and each value is an object defining the values for the enum. Enum IDs shall be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub enums: HashMap<String, EnumDefinition>,

    /// Unique identifier for the schema. Schema IDs shall be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
    pub id: String,

    /// The name of the schema, e.g. for display purposes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// Application-specific version of the schema.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub version: Option<String>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Statistics about entities.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Statistics {
    /// A dictionary, where each key corresponds to a class ID in the `classes` dictionary of the metatata schema that was defined for the tileset that contains these statistics. Each value is an object containing statistics about entities that conform to the class.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub classes: HashMap<String, ClassStatistics>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An object describing the location of subtree files.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Subtrees {
    /// A template URI pointing to subtree files. A subtree is a fixed-depth (defined by `subtreeLevels`) portion of the tree to keep memory use bounded. The URI of each file is substituted with the subtree root's global level, x, and y. For subdivision scheme `OCTREE`, z shall also be given. Relative paths are relative to the tileset JSON.
    pub uri: String,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A tile in a 3D Tiles tileset.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Tile {
    /// The bounding volume that encloses the tile.
    #[serde(rename = "boundingVolume")]
    pub bounding_volume: BoundingVolume,

    /// An array of objects that define child tiles. Each child tile content is fully enclosed by its parent tile's bounding volume and, generally, has a geometricError less than its parent tile's geometricError. For leaf tiles, there are no children, and this property may not be defined.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub children: Vec<Tile>,

    /// Metadata about the tile's content and a link to the content. When this is omitted the tile is just used for culling. When this is defined, then `contents` shall be undefined.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub content: Option<Content>,

    /// An array of contents. When this is defined, then `content` shall be undefined.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub contents: Vec<Content>,

    /// The error, in meters, introduced if this tile is rendered and its children are not. At runtime, the geometric error is used to compute screen space error (SSE), i.e., the error measured in pixels.
    #[serde(rename = "geometricError")]
    pub geometric_error: f64,

    /// An object that describes the implicit subdivision of this tile.
    #[serde(
        rename = "implicitTiling",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub implicit_tiling: Option<ImplicitTiling>,

    /// Specifies if additive or replacement refinement is used when traversing the tileset for rendering. This property is required for the root tile of a tileset; it is optional for all other tiles. The default is to inherit from the parent tile.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub refine: Option<serde_json::Value>,

    /// A floating-point 4x4 affine transformation matrix, stored in column-major order, that transforms the tile's content--i.e., its features as well as content.boundingVolume, boundingVolume, and viewerRequestVolume--from the tile's local coordinate system to the parent tile's coordinate system, or, in the case of a root tile, from the tile's local coordinate system to the tileset's coordinate system. `transform` does not apply to any volume property when the volume is a region, defined in EPSG:4979 coordinates. `transform` scales the `geometricError` by the maximum scaling factor from the matrix.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub transform: Vec<f64>,

    /// Optional bounding volume that defines the volume the viewer shall be inside of before the tile's content will be requested and before the tile will be refined based on geometricError.
    #[serde(
        rename = "viewerRequestVolume",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub viewer_request_volume: Option<BoundingVolume>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A 3D Tiles tileset.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Tileset {
    /// Metadata about the entire tileset.
    pub asset: Asset,

    /// Names of 3D Tiles extensions required to properly load this tileset. Each element of this array shall also be contained in `extensionsUsed`.
    #[serde(
        rename = "extensionsRequired",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub extensions_required: Vec<String>,

    /// Names of 3D Tiles extensions used somewhere in this tileset.
    #[serde(
        rename = "extensionsUsed",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub extensions_used: Vec<String>,

    /// The error, in meters, introduced if this tileset is not rendered. At runtime, the geometric error is used to compute screen space error (SSE), i.e., the error measured in pixels.
    #[serde(rename = "geometricError")]
    pub geometric_error: f64,

    /// An array of groups that tile content may belong to. Each element of this array is a metadata entity that describes the group. The tile content `group` property is an index into this array.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub groups: Vec<Group>,

    /// A dictionary object of metadata about per-feature properties.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub properties: HashMap<String, Properties>,

    /// The root tile.
    pub root: Tile,

    /// An object defining the structure of metadata classes and enums. When this is defined, then `schemaUri` shall be undefined.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub schema: Option<Schema>,

    /// The URI (or IRI) of the external schema file. When this is defined, then `schema` shall be undefined.
    #[serde(rename = "schemaUri", skip_serializing_if = "Option::is_none", default)]
    pub schema_uri: Option<String>,

    /// An object containing statistics about metadata entities.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub statistics: Option<Statistics>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}
