"""Type stubs for ``i3s.spec`` — I3S layer document types."""

from __future__ import annotations

from enum import IntEnum
from typing import Any

import numpy as np
import numpy.typing as npt

class SceneLayerType(IntEnum):
    ThreeDObject = 0
    IntegratedMesh = 1
    Point = 2
    PointCloud = 3
    Building = 4
    def __repr__(self) -> str: ...

class SceneLayerCapabilities(IntEnum):
    View = 0
    Query = 1
    Edit = 2
    Extract = 3
    def __repr__(self) -> str: ...

class FieldType(IntEnum):
    Date = 0
    Single = 1
    Double = 2
    GUID = 3
    GlobalID = 4
    Integer = 5
    OID = 6
    SmallInteger = 7
    String = 8
    def __repr__(self) -> str: ...

class LodSelectionMetricType(IntEnum):
    MaxScreenThreshold = 0
    MaxScreenThresholdSQ = 1
    ScreenSpaceRelative = 2
    DistanceRangeFromDefaultCamera = 3
    EffectiveDensity = 4
    def __repr__(self) -> str: ...

class SpatialReference:
    @property
    def wkid(self) -> int | None: ...
    @property
    def latest_wkid(self) -> int | None: ...
    @property
    def vcs_wkid(self) -> int | None: ...
    @property
    def latest_vcs_wkid(self) -> int | None: ...
    @property
    def wkt(self) -> str | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class OrientedBoundingBox:
    """I3S OBB from the spec layer document in geographic / CRS coordinates."""
    @property
    def center(self) -> npt.NDArray[np.float64]: ...
    @property
    def half_size(self) -> npt.NDArray[np.float64]: ...
    @property
    def quaternion(self) -> npt.NDArray[np.float64]: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class FullExtent:
    @property
    def xmin(self) -> float: ...
    @property
    def ymin(self) -> float: ...
    @property
    def xmax(self) -> float: ...
    @property
    def ymax(self) -> float: ...
    @property
    def zmin(self) -> float: ...
    @property
    def zmax(self) -> float: ...
    @property
    def spatial_reference(self) -> SpatialReference | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class HeightModelInfo:
    @property
    def height_model(self) -> str | None: ...
    @property
    def vert_crs(self) -> str | None: ...
    @property
    def height_unit(self) -> str | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class ElevationInfo:
    @property
    def mode(self) -> str | None: ...
    @property
    def offset(self) -> float | None: ...
    @property
    def unit(self) -> str | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class Field:
    @property
    def name(self) -> str: ...
    @property
    def alias(self) -> str | None: ...
    @property
    def field_type(self) -> FieldType: ...
    @property
    def field_type_str(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class AttributeStorageInfo:
    @property
    def key(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def ordering(self) -> str | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class LodSelection:
    @property
    def metric_type(self) -> LodSelectionMetricType: ...
    @property
    def metric_type_str(self) -> str: ...
    @property
    def max_error(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class NodePageDefinition:
    @property
    def nodes_per_page(self) -> int: ...
    @property
    def root_index(self) -> int | None: ...
    @property
    def lod_selection_metric_type(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class GeometryDefinition:
    @property
    def topology(self) -> str | None: ...
    @property
    def geometry_buffers(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class MaterialDefinitions:
    @property
    def alpha_mode(self) -> str | None: ...
    @property
    def alpha_cutoff(self) -> float | None: ...
    @property
    def double_sided(self) -> bool | None: ...
    @property
    def cull_face(self) -> str | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class TextureSetDefinition:
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class Store:
    @property
    def id(self) -> str | None: ...
    @property
    def profile(self) -> str: ...
    @property
    def root_node(self) -> str | None: ...
    @property
    def version(self) -> str: ...
    @property
    def index_crs(self) -> str | None: ...
    @property
    def vertex_crs(self) -> str | None: ...
    @property
    def extent(self) -> npt.NDArray[np.float64] | None: ...
    @property
    def normal_reference_frame(self) -> str | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class StorePsl:
    @property
    def id(self) -> str | None: ...
    @property
    def profile(self) -> str: ...
    @property
    def root_node(self) -> str | None: ...
    @property
    def version(self) -> str: ...
    @property
    def index_crs(self) -> str | None: ...
    @property
    def vertex_crs(self) -> str | None: ...
    @property
    def extent(self) -> npt.NDArray[np.float64] | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class MeshLayerInfo:
    """Metadata for a 3DObject or IntegratedMesh scene layer."""
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def alias(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def copyright_text(self) -> str | None: ...
    @property
    def version(self) -> str: ...
    @property
    def href(self) -> str | None: ...
    @property
    def z_factor(self) -> float | None: ...
    @property
    def disable_popup(self) -> bool | None: ...
    @property
    def layer_type(self) -> SceneLayerType: ...
    @property
    def capabilities(self) -> SceneLayerCapabilities: ...
    @property
    def spatial_reference(self) -> SpatialReference | None: ...
    @property
    def height_model_info(self) -> HeightModelInfo | None: ...
    @property
    def elevation_info(self) -> ElevationInfo | None: ...
    @property
    def full_extent(self) -> FullExtent | None: ...
    @property
    def store(self) -> Store: ...
    @property
    def fields(self) -> list[Field]: ...
    @property
    def attribute_storage_info(self) -> list[AttributeStorageInfo]: ...
    @property
    def node_pages(self) -> NodePageDefinition | None: ...
    @property
    def geometry_definitions(self) -> list[GeometryDefinition]: ...
    @property
    def material_definitions(self) -> list[MaterialDefinitions]: ...
    @property
    def texture_set_definitions(self) -> list[TextureSetDefinition]: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class PointLayerInfo:
    """Metadata for a Point (PSL) scene layer."""
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def alias(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def copyright_text(self) -> str | None: ...
    @property
    def version(self) -> str: ...
    @property
    def href(self) -> str | None: ...
    @property
    def z_factor(self) -> float | None: ...
    @property
    def disable_popup(self) -> bool | None: ...
    @property
    def layer_type(self) -> SceneLayerType: ...
    @property
    def capabilities(self) -> SceneLayerCapabilities: ...
    @property
    def spatial_reference(self) -> SpatialReference | None: ...
    @property
    def height_model_info(self) -> HeightModelInfo | None: ...
    @property
    def elevation_info(self) -> ElevationInfo | None: ...
    @property
    def store(self) -> StorePsl: ...
    @property
    def fields(self) -> list[Field]: ...
    @property
    def attribute_storage_info(self) -> list[AttributeStorageInfo]: ...
    @property
    def node_pages(self) -> NodePageDefinition | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class PointCloudLayerInfo:
    """Metadata for a PointCloud (PCSL) scene layer."""
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def alias(self) -> str | None: ...
    @property
    def desc(self) -> str | None: ...
    @property
    def copyright_text(self) -> str | None: ...
    @property
    def layer_type(self) -> SceneLayerType: ...
    @property
    def spatial_reference(self) -> SpatialReference: ...
    @property
    def height_model_info(self) -> HeightModelInfo | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class BuildingLayerInfo:
    """Metadata for a Building (BLD) scene layer."""
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def alias(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def copyright_text(self) -> str | None: ...
    @property
    def layer_type(self) -> SceneLayerType: ...
    @property
    def spatial_reference(self) -> SpatialReference: ...
    @property
    def full_extent(self) -> FullExtent: ...
    @property
    def height_model_info(self) -> HeightModelInfo | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class LayerInfo:
    """Typed layer document. Obtain via ``SceneLayer.layer_info``."""
    @property
    def layer_type(self) -> SceneLayerType: ...
    @property
    def spatial_reference(self) -> SpatialReference | None: ...
    def as_mesh(self) -> MeshLayerInfo | None: ...
    def as_point(self) -> PointLayerInfo | None: ...
    def as_point_cloud(self) -> PointCloudLayerInfo | None: ...
    def as_building(self) -> BuildingLayerInfo | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
