// This file was generated by schema-gen.
// DO NOT EDIT THIS FILE!

//! Generated glTF 2.0 types.

#![allow(clippy::all)]

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// A typed view into a buffer view that contains raw binary data.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Accessor {
    /// The index of the bufferView.
    #[serde(
        rename = "bufferView",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub buffer_view: Option<i32>,

    /// The offset relative to the start of the buffer view in bytes.
    #[serde(rename = "byteOffset", default)]
    pub byte_offset: i64,

    /// The datatype of the accessor's components.
    #[serde(rename = "componentType")]
    pub component_type: serde_json::Value,

    /// The number of elements referenced by this accessor.
    pub count: i64,

    /// Maximum value of each component in this accessor.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub max: Vec<f64>,

    /// Minimum value of each component in this accessor.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub min: Vec<f64>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// Specifies whether integer data values are normalized before usage.
    #[serde(default)]
    pub normalized: bool,

    /// Sparse storage of elements that deviate from their initialization value.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub sparse: Option<AccessorSparse>,

    /// Specifies if the accessor's elements are scalars, vectors, or matrices.
    #[serde(rename = "type")]
    pub r#type: serde_json::Value,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Sparse storage of accessor values that deviate from their initialization value.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AccessorSparse {
    /// Number of deviating accessor values stored in the sparse array.
    pub count: i64,

    /// An object pointing to a buffer view containing the indices of deviating accessor values. The number of indices is equal to `count`. Indices **MUST** strictly increase.
    pub indices: AccessorSparseIndices,

    /// An object pointing to a buffer view containing the deviating accessor values.
    pub values: AccessorSparseValues,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An object pointing to a buffer view containing the indices of deviating accessor values. The number of indices is equal to `accessor.sparse.count`. Indices **MUST** strictly increase.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AccessorSparseIndices {
    /// The index of the buffer view with sparse indices. The referenced buffer view **MUST NOT** have its `target` or `byteStride` properties defined. The buffer view and the optional `byteOffset` **MUST** be aligned to the `componentType` byte length.
    #[serde(rename = "bufferView")]
    pub buffer_view: i32,

    /// The offset relative to the start of the buffer view in bytes.
    #[serde(rename = "byteOffset", default)]
    pub byte_offset: i64,

    /// The indices data type.
    #[serde(rename = "componentType")]
    pub component_type: serde_json::Value,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An object pointing to a buffer view containing the deviating accessor values. The number of elements is equal to `accessor.sparse.count` times number of components. The elements have the same component type as the base accessor. The elements are tightly packed. Data **MUST** be aligned following the same rules as the base accessor.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AccessorSparseValues {
    /// The index of the bufferView with sparse values. The referenced buffer view **MUST NOT** have its `target` or `byteStride` properties defined.
    #[serde(rename = "bufferView")]
    pub buffer_view: i32,

    /// The offset relative to the start of the bufferView in bytes.
    #[serde(rename = "byteOffset", default)]
    pub byte_offset: i64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A keyframe animation.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Animation {
    /// An array of animation channels. An animation channel combines an animation sampler with a target property being animated. Different channels of the same animation **MUST NOT** have the same targets.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub channels: Vec<AnimationChannel>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// An array of animation samplers. An animation sampler combines timestamps with a sequence of output values and defines an interpolation algorithm.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub samplers: Vec<AnimationSampler>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An animation channel combines an animation sampler with a target property being animated.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AnimationChannel {
    /// The index of a sampler in this animation used to compute the value for the target.
    pub sampler: i32,

    /// The descriptor of the animated property.
    pub target: AnimationChannelTarget,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// The descriptor of the animated property.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AnimationChannelTarget {
    /// The index of the node to animate. When undefined, the animated object **MAY** be defined by an extension.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub node: Option<i32>,

    /// The name of the node's TRS property to animate, or the `"weights"` of the Morph Targets it instantiates. For the `"translation"` property, the values that are provided by the sampler are the translation along the X, Y, and Z axes. For the `"rotation"` property, the values are a quaternion in the order (x, y, z, w), where w is the scalar. For the `"scale"` property, the values are the scaling factors along the X, Y, and Z axes.
    pub path: serde_json::Value,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An animation sampler combines timestamps with a sequence of output values and defines an interpolation algorithm.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AnimationSampler {
    /// The index of an accessor containing keyframe timestamps.
    pub input: i32,

    /// Interpolation algorithm.
    #[serde(default)]
    pub interpolation: serde_json::Value,

    /// The index of an accessor, containing keyframe output values.
    pub output: i32,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Metadata about the glTF asset.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Asset {
    /// A copyright message suitable for display to credit the content creator.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub copyright: Option<String>,

    /// Tool that generated this glTF model.  Useful for debugging.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub generator: Option<String>,

    /// The minimum glTF version in the form of `<major>.<minor>` that this asset targets. This property **MUST NOT** be greater than the asset version.
    #[serde(
        rename = "minVersion",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub min_version: Option<String>,

    /// The glTF version in the form of `<major>.<minor>` that this asset targets.
    pub version: String,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Parameters describing a box shape.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct BoxShape {
    /// The extents of the box in each axis in local space.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub size: Vec<f64>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl BoxShape {
    pub const EXTENSION_NAME: &str = "KHR_implicit_shapes";
}

/// A buffer points to binary geometry, animation, or skins.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Buffer {
    /// The length of the buffer in bytes.
    #[serde(rename = "byteLength")]
    pub byte_length: i64,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The URI (or IRI) of the buffer.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub uri: Option<String>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A view into a buffer generally representing a subset of the buffer.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct BufferView {
    /// The index of the buffer.
    pub buffer: i32,

    /// The length of the bufferView in bytes.
    #[serde(rename = "byteLength")]
    pub byte_length: i64,

    /// The offset into the buffer in bytes.
    #[serde(rename = "byteOffset", default)]
    pub byte_offset: i64,

    /// The stride, in bytes.
    #[serde(
        rename = "byteStride",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub byte_stride: Option<i64>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The hint representing the intended GPU buffer type to use with this buffer view.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub target: Option<serde_json::Value>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A camera's projection.  A node **MAY** reference a camera to apply a transform to place the camera in the scene.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Camera {
    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// An orthographic camera containing properties to create an orthographic projection matrix. This property **MUST NOT** be defined when `perspective` is defined.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub orthographic: Option<CameraOrthographic>,

    /// A perspective camera containing properties to create a perspective projection matrix. This property **MUST NOT** be defined when `orthographic` is defined.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub perspective: Option<CameraPerspective>,

    /// Specifies if the camera uses a perspective or orthographic projection.
    #[serde(rename = "type")]
    pub r#type: serde_json::Value,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An orthographic camera containing properties to create an orthographic projection matrix.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CameraOrthographic {
    /// The floating-point horizontal magnification of the view. This value **MUST NOT** be equal to zero. This value **SHOULD NOT** be negative.
    pub xmag: f64,

    /// The floating-point vertical magnification of the view. This value **MUST NOT** be equal to zero. This value **SHOULD NOT** be negative.
    pub ymag: f64,

    /// The floating-point distance to the far clipping plane. This value **MUST NOT** be equal to zero. `zfar` **MUST** be greater than `znear`.
    pub zfar: f64,

    /// The floating-point distance to the near clipping plane.
    pub znear: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A perspective camera containing properties to create a perspective projection matrix.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CameraPerspective {
    /// The floating-point aspect ratio of the field of view.
    #[serde(
        rename = "aspectRatio",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub aspect_ratio: Option<f64>,

    /// The floating-point vertical field of view in radians. This value **SHOULD** be less than π.
    pub yfov: f64,

    /// The floating-point distance to the far clipping plane.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub zfar: Option<f64>,

    /// The floating-point distance to the near clipping plane.
    pub znear: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Parameters describing a capsule shape.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CapsuleShape {
    /// The distance between the centers of the two capping spheres of capsule.
    #[serde(default = "default_capsule_shape_height")]
    pub height: f64,

    /// The radius of the sphere located at the bottom of the capsule (i.e. the sphere at the half-height along -Y)
    #[serde(
        rename = "radiusBottom",
        default = "default_capsule_shape_radius_bottom"
    )]
    pub radius_bottom: f64,

    /// The radius of the sphere located at the top of the capsule (i.e. the sphere at the half-height along +Y)
    #[serde(rename = "radiusTop", default = "default_capsule_shape_radius_top")]
    pub radius_top: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl CapsuleShape {
    pub const EXTENSION_NAME: &str = "KHR_implicit_shapes";
}

fn default_capsule_shape_height() -> f64 {
    0.5
}

fn default_capsule_shape_radius_bottom() -> f64 {
    0.25
}

fn default_capsule_shape_radius_top() -> f64 {
    0.25
}

/// A class containing a set of properties.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Class {
    /// The description of the class.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,

    /// The name of the class, e.g. for display purposes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// Experimental. The parent class ID.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub parent: Option<String>,

    /// A dictionary, where each key is a property ID and each value is an object defining the property. Property IDs must be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub properties: HashMap<String, ClassProperty>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl Class {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// A class property.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ClassProperty {
    /// Whether the property is an array. When `count` is defined the property is a fixed-length array. Otherwise the property is a variable-length array.
    #[serde(default)]
    pub array: bool,

    /// The datatype of the element's components. Only applicable to `SCALAR`, `VECN`, and `MATN` types.
    #[serde(
        rename = "componentType",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub component_type: Option<serde_json::Value>,

    /// The number of array elements. May only be defined when `array` is true.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub count: Option<i64>,

    /// The description of the property.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,

    /// Enum ID as declared in the `enums` dictionary. Required when `type` is `ENUM`.
    #[serde(rename = "enumType", skip_serializing_if = "Option::is_none", default)]
    pub enum_type: Option<String>,

    /// The name of the property, e.g. for display purposes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// Specifies whether integer values are normalized. Only applicable to `SCALAR`, `VECN`, and `MATN` types with integer component types. For unsigned integer component types, values are normalized between `[0.0, 1.0]`. For signed integer component types, values are normalized between `[-1.0, 1.0]`. For all other component types, this property must be false.
    #[serde(default)]
    pub normalized: bool,

    /// If required, the property must be present in every entity conforming to the class. If not required, individual entities may include `noData` values, or the entire property may be omitted. As a result, `noData` has no effect on a required property. Client implementations may use required properties to make performance optimizations.
    #[serde(default)]
    pub required: bool,

    /// An identifier that describes how this property should be interpreted. The semantic cannot be used by other properties in the class.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub semantic: Option<String>,

    /// The element type.
    #[serde(rename = "type")]
    pub r#type: serde_json::Value,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ClassProperty {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// Parameters describing a cylinder shape.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CylinderShape {
    /// The height of the cylinder, centered along the Y axis.
    #[serde(default = "default_cylinder_shape_height")]
    pub height: f64,

    /// The radius of the bottom of the cylinder (the disk located along -Y.)
    #[serde(
        rename = "radiusBottom",
        default = "default_cylinder_shape_radius_bottom"
    )]
    pub radius_bottom: f64,

    /// The radius of the top of the cylinder (the disk located along +Y.)
    #[serde(rename = "radiusTop", default = "default_cylinder_shape_radius_top")]
    pub radius_top: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl CylinderShape {
    pub const EXTENSION_NAME: &str = "KHR_implicit_shapes";
}

fn default_cylinder_shape_height() -> f64 {
    0.5
}

fn default_cylinder_shape_radius_bottom() -> f64 {
    0.25
}

fn default_cylinder_shape_radius_top() -> f64 {
    0.25
}

/// Common definitions used in schema files.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Definitions {
    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An object defining the values of an enum.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EnumDefinition {
    /// The description of the enum.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,

    /// The name of the enum, e.g. for display purposes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The type of the integer enum value.
    #[serde(rename = "valueType", default)]
    pub value_type: serde_json::Value,

    /// An array of enum values. Duplicate names or duplicate integer values are not allowed.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub values: Vec<EnumValue>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl EnumDefinition {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// An enum value.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EnumValue {
    /// The description of the enum value.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,

    /// The name of the enum value.
    pub name: String,

    /// The integer enum value.
    pub value: i64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl EnumValue {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// Feature IDs stored in a GPU mesh instancing attribute
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtInstanceFeaturesFeatureId {
    /// An attribute containing feature IDs. When this is omitted, then the feature IDs are assigned to the GPU instances by their index.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub attribute: Option<i64>,

    /// The number of unique features in the attribute.
    #[serde(rename = "featureCount")]
    pub feature_count: i64,

    /// A label assigned to this feature ID set. Labels must be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub label: Option<String>,

    /// A value that indicates that no feature is associated with this instance.
    #[serde(
        rename = "nullFeatureId",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub null_feature_id: Option<i64>,

    /// The index of the property table containing per-feature property values. Only applicable when using the `EXT_structural_metadata` extension.
    #[serde(
        rename = "propertyTable",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub property_table: Option<i64>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtInstanceFeaturesFeatureId {
    pub const EXTENSION_NAME: &str = "EXT_instance_features";
}

/// Compressed data for bufferView.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionBufferExtMeshoptCompression {
    /// Set to true to indicate that the buffer is only referenced by bufferViews that have EXT_meshopt_compression extension and as such doesn't need to be loaded.
    #[serde(default)]
    pub fallback: bool,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionBufferExtMeshoptCompression {
    pub const EXTENSION_NAME: &str = "EXT_meshopt_compression";
}

/// Compressed data for bufferView.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionBufferViewExtMeshoptCompression {
    /// The index of the buffer with compressed data.
    pub buffer: i32,

    /// The length of the compressed data in bytes.
    #[serde(rename = "byteLength")]
    pub byte_length: i64,

    /// The offset into the buffer in bytes.
    #[serde(rename = "byteOffset", default)]
    pub byte_offset: i64,

    /// The stride, in bytes.
    #[serde(rename = "byteStride")]
    pub byte_stride: i64,

    /// The number of elements.
    pub count: i64,

    /// The compression filter.
    #[serde(default = "default_extension_buffer_view_ext_meshopt_compression_filter")]
    pub filter: String,

    /// The compression mode.
    pub mode: String,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionBufferViewExtMeshoptCompression {
    pub const EXTENSION_NAME: &str = "EXT_meshopt_compression";
}

fn default_extension_buffer_view_ext_meshopt_compression_filter() -> String {
    "NONE".to_string()
}

/// glTF extension for indicating that some edges of a primitive's triangles should be outlined.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionCesiumPrimitiveOutline {
    /// The index of the accessor providing the list of highlighted lines at the edge of this primitive's triangles.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub indices: Option<i32>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionCesiumPrimitiveOutline {
    pub const EXTENSION_NAME: &str = "CESIUM_primitive_outline";
}

/// glTF CESIUM_RTC extension.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionCesiumRtc {
    /// Center that vertex positions are relative to.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub center: Vec<f64>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionCesiumRtc {
    pub const EXTENSION_NAME: &str = "CESIUM_RTC";
}

/// `CESIUM_tile_edges` extension for a primitive in a glTF model.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionCesiumTileEdges {
    /// The index of the accessor containing indices that make up the bottom edge.
    pub bottom: i32,

    /// The index of the accessor containing indices that make up the left edge.
    pub left: i32,

    /// The index of the accessor containing indices that make up the right edge.
    pub right: i32,

    /// The index of the accessor containing indices that make up the top edge.
    pub top: i32,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionCesiumTileEdges {
    pub const EXTENSION_NAME: &str = "CESIUM_tile_edges";
}

/// Extension of `KHR_implicit_shapes.shape` to represent an implicit cylinder region in a glTF model.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionExtImplicitCylinderRegion {
    /// The height of the cylinder in meters along the Y-axis, in meters.
    pub height: f64,

    /// The maximum angle of the cylinder region in radians. In other words, this is the angle where the cylinder region ends. Must be in the range [-pi, pi].
    #[serde(
        rename = "maxAngle",
        default = "default_extension_ext_implicit_cylinder_region_max_angle"
    )]
    pub max_angle: f64,

    /// The outer radius of the cylinder region along the X and Z axes, in meters.
    #[serde(rename = "maxRadius")]
    pub max_radius: f64,

    /// The minimum angle of the cylinder region in radians. In other words, this is the angle where the cylinder region starts. Must be in the range [-pi, pi].
    #[serde(
        rename = "minAngle",
        default = "default_extension_ext_implicit_cylinder_region_min_angle"
    )]
    pub min_angle: f64,

    /// The inner radius of the cylinder region along the X and Z axes, in meters.
    #[serde(rename = "minRadius")]
    pub min_radius: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionExtImplicitCylinderRegion {
    pub const EXTENSION_NAME: &str = "EXT_implicit_cylinder_region";
}

fn default_extension_ext_implicit_cylinder_region_max_angle() -> f64 {
    3.14159265359
}

fn default_extension_ext_implicit_cylinder_region_min_angle() -> f64 {
    -3.14159265359
}

/// Extension of `KHR_implicit_shapes.shape` to represent an implicit ellipsoid region in a glTF model.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionExtImplicitEllipsoidRegion {
    /// The maximum height of the region relative to the ellipsoid's surface, in meters. May be negative.
    #[serde(rename = "maxHeight")]
    pub max_height: f64,

    /// The maximum latitude (a.k.a. polar angle) of the region, in radians. Must be in the range [-pi/2, pi/2].
    #[serde(
        rename = "maxLatitude",
        default = "default_extension_ext_implicit_ellipsoid_region_max_latitude"
    )]
    pub max_latitude: f64,

    /// The maximum longitude (a.k.a. azimuthal angle) of the region, in radians. Must be in the range [-pi, pi].
    #[serde(
        rename = "maxLongitude",
        default = "default_extension_ext_implicit_ellipsoid_region_max_longitude"
    )]
    pub max_longitude: f64,

    /// The minimum height of the region relative to the ellipsoid's surface, in meters. May be negative.
    #[serde(rename = "minHeight")]
    pub min_height: f64,

    /// The minimum latitude (a.k.a. polar angle) of the region, in radians. Must be in the range [-pi/2, pi/2].
    #[serde(
        rename = "minLatitude",
        default = "default_extension_ext_implicit_ellipsoid_region_min_latitude"
    )]
    pub min_latitude: f64,

    /// The minimum longitude (a.k.a. azimuthal angle) of the region, in radians. Must be in the range [-pi, pi].
    #[serde(
        rename = "minLongitude",
        default = "default_extension_ext_implicit_ellipsoid_region_min_longitude"
    )]
    pub min_longitude: f64,

    /// The radius along the semi-major axis of the reference ellipsoid in meters. Corresponds to the radii along the X and Z axes.
    #[serde(rename = "semiMajorAxisRadius")]
    pub semi_major_axis_radius: f64,

    /// The radius along the semi-minor axis of the reference ellipsoid in meters. Corresponds to the radius along the Y-axis.
    #[serde(rename = "semiMinorAxisRadius")]
    pub semi_minor_axis_radius: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionExtImplicitEllipsoidRegion {
    pub const EXTENSION_NAME: &str = "EXT_implicit_ellipsoid_region";
}

fn default_extension_ext_implicit_ellipsoid_region_max_latitude() -> f64 {
    1.57079632679
}

fn default_extension_ext_implicit_ellipsoid_region_max_longitude() -> f64 {
    3.14159265359
}

fn default_extension_ext_implicit_ellipsoid_region_min_latitude() -> f64 {
    -1.57079632679
}

fn default_extension_ext_implicit_ellipsoid_region_min_longitude() -> f64 {
    -3.14159265359
}

/// An object describing per-instance feature IDs.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionExtInstanceFeatures {
    /// An array of feature ID sets.
    #[serde(rename = "featureIds", skip_serializing_if = "Vec::is_empty", default)]
    pub feature_ids: Vec<ExtInstanceFeaturesFeatureId>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionExtInstanceFeatures {
    pub const EXTENSION_NAME: &str = "EXT_instance_features";
}

/// An object describing feature IDs for a mesh primitive.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionExtMeshFeatures {
    /// An array of feature ID sets.
    #[serde(rename = "featureIds", skip_serializing_if = "Vec::is_empty", default)]
    pub feature_ids: Vec<FeatureId>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionExtMeshFeatures {
    pub const EXTENSION_NAME: &str = "EXT_mesh_features";
}

/// glTF extension defines instance attributes for a node with a mesh.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionExtMeshGpuInstancing {
    /// A dictionary object, where each key corresponds to instance attribute and each value is the index of the accessor containing attribute's data. Attributes TRANSLATION, ROTATION, SCALE define instance transformation. For "TRANSLATION" the values are FLOAT_VEC3's specifying translation along the x, y, and z axes. For "ROTATION" the values are VEC4's specifying rotation as a quaternion in the order (x, y, z, w), where w is the scalar, with component type `FLOAT` or normalized integer. For "SCALE" the values are FLOAT_VEC3's specifying scaling factors along the x, y, and z axes.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub attributes: HashMap<String, i32>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionExtMeshGpuInstancing {
    pub const EXTENSION_NAME: &str = "EXT_mesh_gpu_instancing";
}

/// `EXT_primitive_voxels` extension for a primitive in a glTF model to indicate voxel-based volumetric data
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionExtPrimitiveVoxels {
    /// Dimensions of the voxel grid. The values are interpreted with respect to the shape indicated by `KHR_implicit_shapes`.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub dimensions: Vec<i64>,

    /// A plain JSON object, where each key corresponds to an existing semantic in the primitive's `attributes`, and each value is the attribute's `noData` value. A `noData` value represents missing data — also known as a sentinel value — wherever it appears.
    #[serde(rename = "noData", skip_serializing_if = "HashMap::is_empty", default)]
    pub no_data: HashMap<String, Vec<f64>>,

    /// The optional padding of the voxels.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub padding: Option<Padding>,

    /// The index of the shape in `KHR_implicit_shapes` that the voxel grid adheres to.
    pub shape: i32,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionExtPrimitiveVoxels {
    pub const EXTENSION_NAME: &str = "EXT_primitive_voxels";
}

/// Structural metadata about a glTF element.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionExtStructuralMetadata {
    /// The class that property values conform to. The value shall be a class ID declared in the `classes` dictionary of the metadata schema.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub class: Option<String>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionExtStructuralMetadata {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionKhrDracoMeshCompression {
    /// A dictionary object, where each key corresponds to an attribute and its unique attribute id stored in the compressed geometry.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub attributes: HashMap<String, i32>,

    /// The index of the bufferView.
    #[serde(rename = "bufferView")]
    pub buffer_view: i32,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionKhrDracoMeshCompression {
    pub const EXTENSION_NAME: &str = "KHR_draco_mesh_compression";
}

/// Data defining a 3D Gaussian Splat primitive.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionKhrGaussianSplatting {
    /// Property specifying the color space of the spherical harmonics.
    #[serde(rename = "colorSpace")]
    pub color_space: String,

    /// Property specifying parameters regarding the kernel used to generate the Gaussians.
    pub kernel: String,

    /// Optional property specifying how to project the Gaussians to achieve a perspective correct value. This property defaults to perspective.
    #[serde(default = "default_extension_khr_gaussian_splatting_projection")]
    pub projection: String,

    /// Optional property specifying how to sort the Gaussians during rendering. This property defaults to cameraDistance.
    #[serde(
        rename = "sortingMethod",
        default = "default_extension_khr_gaussian_splatting_sorting_method"
    )]
    pub sorting_method: String,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionKhrGaussianSplatting {
    pub const EXTENSION_NAME: &str = "KHR_gaussian_splatting";
}

fn default_extension_khr_gaussian_splatting_projection() -> String {
    "perspective".to_string()
}

fn default_extension_khr_gaussian_splatting_sorting_method() -> String {
    "cameraDistance".to_string()
}

/// Compressed data for SPZ v2 primitive.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionKhrGaussianSplattingCompressionSpz2 {
    /// The index of the bufferView.
    #[serde(rename = "bufferView")]
    pub buffer_view: i32,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionKhrGaussianSplattingCompressionSpz2 {
    pub const EXTENSION_NAME: &str = "KHR_gaussian_splatting";
}

/// Top level implicit shapes.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionKhrImplicitShapes {
    /// An array of shape descriptions.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub shapes: Vec<Shape>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionKhrImplicitShapes {
    pub const EXTENSION_NAME: &str = "KHR_implicit_shapes";
}

/// glTF extension that defines the unlit material model.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionKhrMaterialsUnlit {
    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionKhrMaterialsUnlit {
    pub const EXTENSION_NAME: &str = "KHR_materials_unlit";
}

/// glTF extension to specify textures using the KTX v2 images with Basis Universal supercompression.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionKhrTextureBasisu {
    /// The index of the image which points to a KTX v2 resource with Basis Universal supercompression.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub source: Option<i32>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionKhrTextureBasisu {
    pub const EXTENSION_NAME: &str = "KHR_texture_basisu";
}

/// glTF extension that enables shifting and scaling UV coordinates on a per-texture basis
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionKhrTextureTransform {
    /// The offset of the UV coordinate origin as a factor of the texture dimensions.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub offset: Vec<f64>,

    /// Rotate the UVs by this many radians counter-clockwise around the origin.
    #[serde(default)]
    pub rotation: f64,

    /// The scale factor applied to the components of the UV coordinates.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub scale: Vec<f64>,

    /// Overrides the textureInfo texCoord value if supplied, and if this extension is supported.
    #[serde(rename = "texCoord", skip_serializing_if = "Option::is_none", default)]
    pub tex_coord: Option<i64>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionKhrTextureTransform {
    pub const EXTENSION_NAME: &str = "KHR_texture_transform";
}

/// Structural metadata about a glTF primitive.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionMeshPrimitiveExtStructuralMetadata {
    /// An array of indexes of property attributes in the root `EXT_structural_metadata` object.
    #[serde(
        rename = "propertyAttributes",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub property_attributes: Vec<i32>,

    /// An array of indexes of property textures in the root `EXT_structural_metadata` object.
    #[serde(
        rename = "propertyTextures",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub property_textures: Vec<i32>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionMeshPrimitiveExtStructuralMetadata {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionMeshPrimitiveKhrMaterialsVariants {
    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionMeshPrimitiveKhrMaterialsVariants {
    pub const EXTENSION_NAME: &str = "KHR_materials_variants";
}

/// glTF extension that provides structural metadata about vertices, texels, and features in a glTF asset.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionModelExtStructuralMetadata {
    /// An array of property attribute definitions, which may be referenced by index.
    #[serde(
        rename = "propertyAttributes",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub property_attributes: Vec<PropertyAttribute>,

    /// An array of property table definitions, which may be referenced by index.
    #[serde(
        rename = "propertyTables",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub property_tables: Vec<PropertyTable>,

    /// An array of property texture definitions, which may be referenced by index.
    #[serde(
        rename = "propertyTextures",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub property_textures: Vec<PropertyTexture>,

    /// An object defining classes and enums.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub schema: Option<Schema>,

    /// The URI (or IRI) of the external schema file.
    #[serde(rename = "schemaUri", skip_serializing_if = "Option::is_none", default)]
    pub schema_uri: Option<String>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionModelExtStructuralMetadata {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// glTF extension that defines a material variations for mesh primitives
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionModelKhrMaterialsVariants {
    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionModelKhrMaterialsVariants {
    pub const EXTENSION_NAME: &str = "KHR_materials_variants";
}

/// glTF extension that defines mesh variants for nodes
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionModelMaxarMeshVariants {
    /// The index of the variant to load by default. The meshes that are mapped to the default variant must represent the set of meshes initially selected by the nodes for rendering, as per vanilla glTF behavior.
    pub default: i32,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionModelMaxarMeshVariants {
    pub const EXTENSION_NAME: &str = "MAXAR_mesh_variants";
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionNodeMaxarMeshVariants {
    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionNodeMaxarMeshVariants {
    pub const EXTENSION_NAME: &str = "MAXAR_mesh_variants";
}

/// glTF extension to specify textures using the WebP image format.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExtensionTextureWebp {
    /// The index of the WebP image.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub source: Option<i32>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl ExtensionTextureWebp {
    pub const EXTENSION_NAME: &str = "EXT_texture_webp";
}

/// Feature IDs stored in an attribute or texture.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FeatureId {
    /// An attribute containing feature IDs. When `attribute` and `texture` are omitted the feature IDs are assigned to vertices by their index.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub attribute: Option<i64>,

    /// The number of unique features in the attribute or texture.
    #[serde(rename = "featureCount")]
    pub feature_count: i64,

    /// A label assigned to this feature ID set. Labels must be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub label: Option<String>,

    /// A value that indicates that no feature is associated with this vertex or texel.
    #[serde(
        rename = "nullFeatureId",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub null_feature_id: Option<i64>,

    /// The index of the property table containing per-feature property values. Only applicable when using the `EXT_structural_metadata` extension.
    #[serde(
        rename = "propertyTable",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub property_table: Option<i32>,

    /// A texture containing feature IDs.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub texture: Option<FeatureIdTexture>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl FeatureId {
    pub const EXTENSION_NAME: &str = "EXT_mesh_features";
}

/// An integer value used to construct a string in the format `_FEATURE_ID_<set index>` which is a reference to a key in `EXT_mesh_gpu_instancing.attributes` dictionary (e.g. a value of `0` corresponds to `_FEATURE_ID_0`).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FeatureIdAttributeInExtInstanceFeatures {
    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl FeatureIdAttributeInExtInstanceFeatures {
    pub const EXTENSION_NAME: &str = "EXT_instance_features";
}

/// An integer value used to construct a string in the format `_FEATURE_ID_<set index>` which is a reference to a key in `mesh.primitives.attributes` (e.g. a value of `0` corresponds to `_FEATURE_ID_0`).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FeatureIdAttributeInExtMeshFeatures {
    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl FeatureIdAttributeInExtMeshFeatures {
    pub const EXTENSION_NAME: &str = "EXT_mesh_features";
}

/// A texture containing feature IDs
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FeatureIdTexture {
    /// Texture channels containing feature IDs, identified by index. Feature IDs may be packed into multiple channels if a single channel does not have sufficient bit depth to represent all feature ID values. The values are packed in little-endian order.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub channels: Vec<i64>,

    /// The index of the texture.
    pub index: i32,

    /// The set index of texture's TEXCOORD attribute used for texture coordinate mapping.
    #[serde(rename = "texCoord", default)]
    pub tex_coord: i64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl FeatureIdTexture {
    pub const EXTENSION_NAME: &str = "EXT_mesh_features";
}

/// Image data used to create a texture. Image **MAY** be referenced by an URI (or IRI) or a buffer view index.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Image {
    /// The index of the bufferView that contains the image. This field **MUST NOT** be defined when `uri` is defined.
    #[serde(
        rename = "bufferView",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub buffer_view: Option<i32>,

    /// The image's media type. This field **MUST** be defined when `bufferView` is defined.
    #[serde(rename = "mimeType", skip_serializing_if = "Option::is_none", default)]
    pub mime_type: Option<serde_json::Value>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The URI (or IRI) of the image.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub uri: Option<String>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// The material appearance of a primitive.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Material {
    /// The alpha cutoff value of the material.
    #[serde(rename = "alphaCutoff", default = "default_material_alpha_cutoff")]
    pub alpha_cutoff: f64,

    /// The alpha rendering mode of the material.
    #[serde(rename = "alphaMode", default)]
    pub alpha_mode: serde_json::Value,

    /// Specifies whether the material is double sided.
    #[serde(rename = "doubleSided", default)]
    pub double_sided: bool,

    /// The factors for the emissive color of the material.
    #[serde(
        rename = "emissiveFactor",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub emissive_factor: Vec<f64>,

    /// The emissive texture.
    #[serde(
        rename = "emissiveTexture",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub emissive_texture: Option<TextureInfo>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The tangent space normal texture.
    #[serde(
        rename = "normalTexture",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub normal_texture: Option<MaterialNormalTextureInfo>,

    /// The occlusion texture.
    #[serde(
        rename = "occlusionTexture",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub occlusion_texture: Option<MaterialOcclusionTextureInfo>,

    /// A set of parameter values that are used to define the metallic-roughness material model from Physically Based Rendering (PBR) methodology. When undefined, all the default values of `pbrMetallicRoughness` **MUST** apply.
    #[serde(
        rename = "pbrMetallicRoughness",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub pbr_metallic_roughness: Option<MaterialPbrMetallicRoughness>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

fn default_material_alpha_cutoff() -> f64 {
    0.5
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MaterialNormalTextureInfo {
    /// The index of the texture.
    pub index: i32,

    /// The scalar parameter applied to each normal vector of the normal texture.
    #[serde(default = "default_material_normal_texture_info_scale")]
    pub scale: f64,

    /// The set index of texture's TEXCOORD attribute used for texture coordinate mapping.
    #[serde(rename = "texCoord", default)]
    pub tex_coord: i64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

fn default_material_normal_texture_info_scale() -> f64 {
    1.0
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MaterialOcclusionTextureInfo {
    /// The index of the texture.
    pub index: i32,

    /// A scalar multiplier controlling the amount of occlusion applied.
    #[serde(default = "default_material_occlusion_texture_info_strength")]
    pub strength: f64,

    /// The set index of texture's TEXCOORD attribute used for texture coordinate mapping.
    #[serde(rename = "texCoord", default)]
    pub tex_coord: i64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

fn default_material_occlusion_texture_info_strength() -> f64 {
    1.0
}

/// A set of parameter values that are used to define the metallic-roughness material model from Physically-Based Rendering (PBR) methodology.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MaterialPbrMetallicRoughness {
    /// The factors for the base color of the material.
    #[serde(
        rename = "baseColorFactor",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub base_color_factor: Vec<f64>,

    /// The base color texture.
    #[serde(
        rename = "baseColorTexture",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub base_color_texture: Option<TextureInfo>,

    /// The factor for the metalness of the material.
    #[serde(
        rename = "metallicFactor",
        default = "default_material_pbr_metallic_roughness_metallic_factor"
    )]
    pub metallic_factor: f64,

    /// The metallic-roughness texture.
    #[serde(
        rename = "metallicRoughnessTexture",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub metallic_roughness_texture: Option<TextureInfo>,

    /// The factor for the roughness of the material.
    #[serde(
        rename = "roughnessFactor",
        default = "default_material_pbr_metallic_roughness_roughness_factor"
    )]
    pub roughness_factor: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

fn default_material_pbr_metallic_roughness_metallic_factor() -> f64 {
    1.0
}

fn default_material_pbr_metallic_roughness_roughness_factor() -> f64 {
    1.0
}

/// A set of primitives to be rendered.  Its global transform is defined by a node that references it.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Mesh {
    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// An array of primitives, each defining geometry to be rendered.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub primitives: Vec<MeshPrimitive>,

    /// Array of weights to be applied to the morph targets. The number of array elements **MUST** match the number of morph targets.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub weights: Vec<f64>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Geometry to be rendered with the given material.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MeshPrimitive {
    /// A plain JSON object, where each key corresponds to a mesh attribute semantic and each value is the index of the accessor containing attribute's data.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub attributes: HashMap<String, i32>,

    /// The index of the accessor that contains the vertex indices.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub indices: Option<i32>,

    /// The index of the material to apply to this primitive when rendering.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub material: Option<i32>,

    /// The topology type of primitives to render.
    #[serde(default)]
    pub mode: serde_json::Value,

    /// An array of morph targets.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub targets: Vec<HashMap<String, i32>>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// The root object for a glTF asset.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Model {
    /// An array of accessors.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub accessors: Vec<Accessor>,

    /// An array of keyframe animations.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub animations: Vec<Animation>,

    /// Metadata about the glTF asset.
    pub asset: Asset,

    /// An array of bufferViews.
    #[serde(rename = "bufferViews", skip_serializing_if = "Vec::is_empty", default)]
    pub buffer_views: Vec<BufferView>,

    /// An array of buffers.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub buffers: Vec<Buffer>,

    /// An array of cameras.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub cameras: Vec<Camera>,

    /// Names of glTF extensions required to properly load this asset.
    #[serde(
        rename = "extensionsRequired",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub extensions_required: Vec<String>,

    /// Names of glTF extensions used in this asset.
    #[serde(
        rename = "extensionsUsed",
        skip_serializing_if = "Vec::is_empty",
        default
    )]
    pub extensions_used: Vec<String>,

    /// An array of images.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub images: Vec<Image>,

    /// An array of materials.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub materials: Vec<Material>,

    /// An array of meshes.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub meshes: Vec<Mesh>,

    /// An array of nodes.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub nodes: Vec<Node>,

    /// An array of samplers.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub samplers: Vec<Sampler>,

    /// The index of the default scene.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub scene: Option<i32>,

    /// An array of scenes.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub scenes: Vec<Scene>,

    /// An array of skins.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub skins: Vec<Skin>,

    /// An array of textures.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub textures: Vec<Texture>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// A node in the node hierarchy.  When the node contains `skin`, all `mesh.primitives` **MUST** contain `JOINTS_0` and `WEIGHTS_0` attributes.  A node **MAY** have either a `matrix` or any combination of `translation`/`rotation`/`scale` (TRS) properties. TRS properties are converted to matrices and postmultiplied in the `T * R * S` order to compose the transformation matrix; first the scale is applied to the vertices, then the rotation, and then the translation. If none are provided, the transform is the identity. When a node is targeted for animation (referenced by an animation.channel.target), `matrix` **MUST NOT** be present.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Node {
    /// The index of the camera referenced by this node.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub camera: Option<i32>,

    /// The indices of this node's children.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub children: Vec<i32>,

    /// A floating-point 4x4 transformation matrix stored in column-major order.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub matrix: Vec<f64>,

    /// The index of the mesh in this node.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub mesh: Option<i32>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The node's unit quaternion rotation in the order (x, y, z, w), where w is the scalar.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub rotation: Vec<f64>,

    /// The node's non-uniform scale, given as the scaling factors along the x, y, and z axes.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub scale: Vec<f64>,

    /// The index of the skin referenced by this node.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub skin: Option<i32>,

    /// The node's translation along the x, y, and z axes.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub translation: Vec<f64>,

    /// The weights of the instantiated morph target. The number of array elements **MUST** match the number of morph targets of the referenced mesh. When defined, `mesh` **MUST** also be defined.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub weights: Vec<f64>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// The padding around a voxel grid. Specifies how many rows of attribute data come from neighboring grids in each dimension.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Padding {
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub after: Vec<i64>,

    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub before: Vec<i64>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Properties conforming to a class, organized as property values stored in attributes.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PropertyAttribute {
    /// The class that property values conform to. The value must be a class ID declared in the `classes` dictionary.
    pub class: String,

    /// The name of the property attribute, e.g. for display purposes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// A dictionary, where each key corresponds to a property ID in the class' `properties` dictionary and each value is an object describing where property values are stored. Required properties must be included in this dictionary.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub properties: HashMap<String, PropertyAttributeProperty>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl PropertyAttribute {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// An attribute containing property values.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PropertyAttributeProperty {
    /// The name of the attribute containing property values.
    pub attribute: String,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl PropertyAttributeProperty {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// Properties conforming to a class, organized as property values stored in binary columnar arrays.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PropertyTable {
    /// The class that property values conform to. The value must be a class ID declared in the `classes` dictionary.
    pub class: String,

    /// The number of elements in each property array.
    pub count: i64,

    /// The name of the property table, e.g. for display purposes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// A dictionary, where each key corresponds to a property ID in the class' `properties` dictionary and each value is an object describing where property values are stored. Required properties must be included in this dictionary.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub properties: HashMap<String, PropertyTableProperty>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl PropertyTable {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// An array of binary property values.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PropertyTableProperty {
    /// The type of values in `arrayOffsets`.
    #[serde(rename = "arrayOffsetType", default)]
    pub array_offset_type: serde_json::Value,

    /// The index of the buffer view containing offsets for variable-length arrays. The number of offsets is equal to the property table `count` plus one. The offsets represent the start positions of each array, with the last offset representing the position after the last array. The array length is computed using the difference between the subsequent offset and the current offset. If `type` is `STRING` the offsets index into the string offsets array (stored in `stringOffsets`), otherwise they index into the property array (stored in `values`). The data type of these offsets is determined by `arrayOffsetType`. The buffer view `byteOffset` must be aligned to a multiple of the `arrayOffsetType` size.
    #[serde(
        rename = "arrayOffsets",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub array_offsets: Option<i32>,

    /// The type of values in `stringOffsets`.
    #[serde(rename = "stringOffsetType", default)]
    pub string_offset_type: serde_json::Value,

    /// The index of the buffer view containing offsets for strings. The number of offsets is equal to the number of string elements plus one. The offsets represent the byte offsets of each string in the property array (stored in `values`), with the last offset representing the byte offset after the last string. The string byte length is computed using the difference between the subsequent offset and the current offset. The data type of these offsets is determined by `stringOffsetType`. The buffer view `byteOffset` must be aligned to a multiple of the `stringOffsetType` size.
    #[serde(
        rename = "stringOffsets",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub string_offsets: Option<i32>,

    /// The index of the buffer view containing property values. The data type of property values is determined by the property definition: When `type` is `BOOLEAN` values are packed into a bitstream. When `type` is `STRING` values are stored as byte sequences and decoded as UTF-8 strings. When `type` is `SCALAR`, `VECN`, or `MATN` the values are stored as the provided `componentType` and the buffer view `byteOffset` must be aligned to a multiple of the `componentType` size. When `type` is `ENUM` values are stored as the enum's `valueType` and the buffer view `byteOffset` must be aligned to a multiple of the `valueType` size. Each enum value in the array must match one of the allowed values in the enum definition. `arrayOffsets` is required for variable-length arrays and `stringOffsets` is required for strings (for variable-length arrays of strings, both are required).
    pub values: i32,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl PropertyTableProperty {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// Properties conforming to a class, organized as property values stored in textures.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PropertyTexture {
    /// The class that property values conform to. The value must be a class ID declared in the `classes` dictionary.
    pub class: String,

    /// The name of the property texture, e.g. for display purposes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// A dictionary, where each key corresponds to a property ID in the class' `properties` dictionary and each value is an object describing where property values are stored. Required properties must be included in this dictionary.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub properties: HashMap<String, PropertyTextureProperty>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl PropertyTexture {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// A texture containing property values.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PropertyTextureProperty {
    /// Texture channels containing property values, identified by index. The values may be packed into multiple channels if a single channel does not have sufficient bit depth. The values are packed in little-endian order.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub channels: Vec<i64>,

    /// The index of the texture.
    pub index: i32,

    /// The set index of texture's TEXCOORD attribute used for texture coordinate mapping.
    #[serde(rename = "texCoord", default)]
    pub tex_coord: i64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl PropertyTextureProperty {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// Texture sampler properties for filtering and wrapping modes.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Sampler {
    /// Magnification filter.
    #[serde(rename = "magFilter", skip_serializing_if = "Option::is_none", default)]
    pub mag_filter: Option<serde_json::Value>,

    /// Minification filter.
    #[serde(rename = "minFilter", skip_serializing_if = "Option::is_none", default)]
    pub min_filter: Option<serde_json::Value>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// S (U) wrapping mode.
    #[serde(rename = "wrapS", default)]
    pub wrap_s: serde_json::Value,

    /// T (V) wrapping mode.
    #[serde(rename = "wrapT", default)]
    pub wrap_t: serde_json::Value,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// The root nodes of a scene.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Scene {
    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The indices of each root node.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub nodes: Vec<i32>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// An object defining classes and enums.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Schema {
    /// A dictionary, where each key is a class ID and each value is an object defining the class. Class IDs must be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub classes: HashMap<String, Class>,

    /// The description of the schema.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,

    /// A dictionary, where each key is an enum ID and each value is an object defining the values for the enum. Enum IDs must be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
    #[serde(skip_serializing_if = "HashMap::is_empty", default)]
    pub enums: HashMap<String, EnumDefinition>,

    /// Unique identifier for the schema. Schema IDs must be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
    pub id: String,

    /// The name of the schema, e.g. for display purposes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// Application-specific version of the schema.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub version: Option<String>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl Schema {
    pub const EXTENSION_NAME: &str = "EXT_structural_metadata";
}

/// Parameters describing an implicit shape.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Shape {
    /// A set of parameter values that are used to define a box shape.
    #[serde(rename = "box", skip_serializing_if = "Option::is_none", default)]
    pub r#box: Option<BoxShape>,

    /// A set of parameter values that are used to define a capsule shape.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub capsule: Option<CapsuleShape>,

    /// A set of parameter values that are used to define a cylinder shape.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub cylinder: Option<CylinderShape>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// A set of parameter values that are used to define a sphere shape.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub sphere: Option<SphereShape>,

    /// Specifies the shape type.
    #[serde(rename = "type")]
    pub r#type: serde_json::Value,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl Shape {
    pub const EXTENSION_NAME: &str = "KHR_implicit_shapes";
}

/// Joints and matrices defining a skin.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Skin {
    /// The index of the accessor containing the floating-point 4x4 inverse-bind matrices.
    #[serde(
        rename = "inverseBindMatrices",
        skip_serializing_if = "Option::is_none",
        default
    )]
    pub inverse_bind_matrices: Option<i32>,

    /// Indices of skeleton nodes, used as joints in this skin.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub joints: Vec<i32>,

    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The index of the node used as a skeleton root.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub skeleton: Option<i32>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Parameters describing a sphere shape.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SphereShape {
    /// The radius of the sphere.
    #[serde(default = "default_sphere_shape_radius")]
    pub radius: f64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

impl SphereShape {
    pub const EXTENSION_NAME: &str = "KHR_implicit_shapes";
}

fn default_sphere_shape_radius() -> f64 {
    0.5
}

/// A texture and its sampler.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Texture {
    /// The user-defined name of this object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,

    /// The index of the sampler used by this texture. When undefined, a sampler with repeat wrapping and auto filtering **SHOULD** be used.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub sampler: Option<i32>,

    /// The index of the image used by this texture. When undefined, an extension or other mechanism **SHOULD** supply an alternate texture source, otherwise behavior is undefined.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub source: Option<i32>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

/// Reference to a texture.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TextureInfo {
    /// The index of the texture.
    pub index: i32,

    /// The set index of texture's TEXCOORD attribute used for texture coordinate mapping.
    #[serde(rename = "texCoord", default)]
    pub tex_coord: i64,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}
