#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Scheduling context enum exposed to C.
 */
typedef enum orkester_context_t {
  ORKESTER_CONTEXT_BACKGROUND = 0,
  ORKESTER_CONTEXT_MAIN = 1,
  ORKESTER_CONTEXT_IMMEDIATE = 2,
} orkester_context_t;

/**
 * Result code for channel send operations.
 */
typedef enum orkester_send_result_t {
  ORKESTER_SEND_OK = 0,
  ORKESTER_SEND_FULL = 1,
  ORKESTER_SEND_CLOSED = 2,
} orkester_send_result_t;

typedef void *orkester_cancel_token_t;

typedef void *orkester_sender_t;

typedef void *orkester_receiver_t;

/**
 * Opaque async runtime handle. Wraps `orkester::Runtime`.
 */
typedef struct orkester_t {
  uint8_t _opaque;
} orkester_t;

/**
 * Callback for fire-and-forget operations — `void(*)(void*)`.
 */
typedef void (*orkester_callback_fn_t)(void*);

/**
 * Dispatch function type for scheduling work on a background thread.
 */
typedef void (*orkester_dispatch_fn_t)(void *ctx, orkester_callback_fn_t work, void *work_data);

/**
 * Opaque handle to a `Task<Payload>`.
 */
typedef void *orkester_task_t;

typedef void *orkester_join_set_t;

/**
 * Opaque handle to a `MainThreadScope`.
 */
typedef void *orkester_main_scope_t;

/**
 * Opaque handle to a `Resolver<Payload>`.
 */
typedef void *orkester_resolver_t;

/**
 * Returned by `orkester_resolver_create`.
 */
typedef struct orkester_resolver_pair_t {
  orkester_resolver_t resolver;
  orkester_task_t task;
} orkester_resolver_pair_t;

typedef orkester_task_t (*orkester_retry_fn_t)(void *ctx);

typedef void *orkester_semaphore_permit_t;

typedef void *orkester_semaphore_t;

/**
 * Error-catch callback that receives an opaque error pointer
 * and returns an `orkester_task_t`.
 * The callback does NOT take ownership of `error`.
 */
typedef orkester_task_t (*orkester_catch_fn_t)(void *ctx, void *error);

/**
 * Async-transform callback for continuations.
 * Receives `(ctx, input_value)`, returns an `orkester_task_t`.
 * The callback takes ownership of `input_value`.
 * Returning null is treated as resolving with an empty payload.
 */
typedef orkester_task_t (*orkester_then_fn_t)(void *ctx, void *value);

/**
 * Opaque handle to a `ThreadPool`.
 */
typedef void *orkester_thread_pool_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void orkester_cancel_token_cancel(orkester_cancel_token_t token);

orkester_cancel_token_t orkester_cancel_token_clone(orkester_cancel_token_t token);

orkester_cancel_token_t orkester_cancel_token_create(void);

void orkester_cancel_token_drop(orkester_cancel_token_t token);

bool orkester_cancel_token_is_cancelled(orkester_cancel_token_t token);

void orkester_channel_create(size_t capacity,
                             orkester_sender_t *out_sender,
                             orkester_receiver_t *out_receiver);

void orkester_channel_create_oneshot(orkester_sender_t *out_sender,
                                     orkester_receiver_t *out_receiver);

/**
 * Clone a `Runtime` (cheap Arc clone).
 */
struct orkester_t *orkester_clone(const struct orkester_t *ptr);

/**
 * Create a `Runtime` from a dispatch function.
 */
struct orkester_t *orkester_create(orkester_dispatch_fn_t dispatch,
                                   void *ctx,
                                   void (*destroy)(void*));

/**
 * Create a `Runtime` with a built-in thread pool.
 */
struct orkester_t *orkester_create_default(size_t num_threads);

/**
 * Create a task that completes after `millis` milliseconds.
 */
orkester_task_t orkester_delay(const struct orkester_t *system, uint64_t millis);

/**
 * Destroy a `Runtime`.
 */
void orkester_destroy(struct orkester_t *ptr);

/**
 * Dispatch all queued main-thread tasks. Returns how many were dispatched.
 */
size_t orkester_dispatch(const struct orkester_t *system);

/**
 * Dispatch a single main-thread task. Returns true if one was dispatched.
 */
bool orkester_dispatch_one(const struct orkester_t *system);

/**
 * Wait for all tasks to complete (void — payloads dropped).
 * Consumes all input handles. Returns a single task.
 */
orkester_task_t orkester_join_all(const struct orkester_t *system,
                                  orkester_task_t *tasks,
                                  size_t count);

/**
 * Wait for all tasks to complete, preserving per-element payloads.
 * Consumes all input handles. Returns a task whose payload is a `ValueArray`.
 */
orkester_task_t orkester_join_all_values(const struct orkester_t *system,
                                         orkester_task_t *tasks,
                                         size_t count);

orkester_join_set_t orkester_join_set_create(const struct orkester_t *system);

void orkester_join_set_drop(orkester_join_set_t js);

size_t orkester_join_set_join_all(orkester_join_set_t js, size_t *out_total);

bool orkester_join_set_join_next(orkester_join_set_t js, bool *out_ok);

size_t orkester_join_set_len(orkester_join_set_t js);

void orkester_join_set_push(orkester_join_set_t js, orkester_task_t task);

/**
 * Enter main-thread scope.
 */
orkester_main_scope_t orkester_main_scope_create(const struct orkester_t *system);

/**
 * Leave main-thread scope. Consumes the handle.
 */
void orkester_main_scope_drop(orkester_main_scope_t scope);

/**
 * Race multiple tasks. Consumes all input handles.
 */
orkester_task_t orkester_race(const struct orkester_t *system,
                              orkester_task_t *tasks,
                              size_t count);

void orkester_receiver_drop(orkester_receiver_t receiver);

bool orkester_receiver_recv(orkester_receiver_t receiver, void **out_value);

/**
 * Create an already-resolved task with no payload.
 */
orkester_task_t orkester_resolved(const struct orkester_t *system);

/**
 * Create an already-resolved task carrying a value.
 */
orkester_task_t orkester_resolved_with_destroy(const struct orkester_t *system,
                                               void *value,
                                               void (*destroy_fn)(void*));

/**
 * Create a resolver/task pair.
 */
struct orkester_resolver_pair_t orkester_resolver_create(const struct orkester_t *system);

/**
 * Drop a resolver without resolving (auto-rejects the paired task).
 */
void orkester_resolver_drop(orkester_resolver_t resolver);

/**
 * Reject with a string message. Consumes the resolver handle.
 */
void orkester_resolver_reject(orkester_resolver_t resolver,
                              const char *message,
                              size_t message_len);

/**
 * Reject with an opaque error object. Consumes the resolver handle.
 */
void orkester_resolver_reject_opaque(orkester_resolver_t resolver,
                                     void *error,
                                     void (*destroy)(void*));

/**
 * Resolve with no payload (void). Consumes the resolver handle.
 */
void orkester_resolver_resolve_empty(orkester_resolver_t resolver);

/**
 * Resolve with a value payload. Consumes the resolver handle.
 */
void orkester_resolver_resolve_with(orkester_resolver_t resolver,
                                    void *value,
                                    void (*destroy)(void*));

/**
 * Retry an operation up to `max_attempts` times with exponential back-off.
 */
orkester_task_t orkester_retry(const struct orkester_t *system,
                               uint32_t max_attempts,
                               orkester_retry_fn_t factory,
                               void *ctx);

orkester_semaphore_permit_t orkester_semaphore_acquire(orkester_semaphore_t sem);

size_t orkester_semaphore_available(orkester_semaphore_t sem);

orkester_semaphore_t orkester_semaphore_create(const struct orkester_t *system, size_t permits);

void orkester_semaphore_drop(orkester_semaphore_t sem);

void orkester_semaphore_permit_drop(orkester_semaphore_permit_t permit);

orkester_semaphore_permit_t orkester_semaphore_try_acquire(orkester_semaphore_t sem);

orkester_sender_t orkester_sender_clone(orkester_sender_t sender);

void orkester_sender_drop(orkester_sender_t sender);

enum orkester_send_result_t orkester_sender_send(orkester_sender_t sender,
                                                 void *value,
                                                 void **out_value);

enum orkester_send_result_t orkester_sender_try_send(orkester_sender_t sender,
                                                     void *value,
                                                     void **out_value);

/**
 * Spawn a detached task. Fire-and-forget.
 */
void orkester_spawn(const struct orkester_t *system,
                    enum orkester_context_t context,
                    orkester_callback_fn_t callback,
                    void *ctx);

/**
 * Free a string previously returned by orkester FFI error functions.
 */
void orkester_string_drop(const char *ptr, size_t len);

/**
 * Attach a cancellation token to a task. Consumes the task handle.
 */
orkester_task_t orkester_task_cancel(orkester_task_t task, orkester_cancel_token_t token);

/**
 * Attach an error-catch handler. The callback receives an opaque error
 * pointer and returns an `orkester_task_t`. Consumes the input task handle.
 */
orkester_task_t orkester_task_catch(orkester_task_t task,
                                    enum orkester_context_t context,
                                    orkester_catch_fn_t callback,
                                    void *ctx);

/**
 * Attach an async-transform continuation. The callback receives the input
 * value and returns an `orkester_task_t`. Consumes the input task handle.
 */
orkester_task_t orkester_task_chain(orkester_task_t task,
                                    enum orkester_context_t context,
                                    orkester_then_fn_t transform,
                                    void *ctx);

/**
 * Attach an async-transform continuation in a thread pool.
 * Consumes the input task handle.
 */
orkester_task_t orkester_task_chain_in_pool(orkester_task_t task,
                                            orkester_thread_pool_t pool,
                                            orkester_then_fn_t transform,
                                            void *ctx);

/**
 * Clone a shared task handle.
 */
orkester_task_t orkester_task_clone(orkester_task_t task);

/**
 * Drop a task handle.
 */
void orkester_task_drop(orkester_task_t task);

/**
 * Check if a task is ready.
 */
bool orkester_task_is_ready(orkester_task_t task);

/**
 * Convert a task to a shared task. Consumes the task handle.
 * `clone_fn` is used to clone the payload for shared access.
 * Pass null if sharing is only used for fan-out without accessing the value.
 */
orkester_task_t orkester_task_share(orkester_task_t task, void *(*clone_fn)(void*));

/**
 * Block until a task completes. Consumes the handle.
 * On success: `out_value` receives the payload value, returns true.
 * On failure: `out_value` receives opaque error ptr (if any),
 *             `out_error_ptr`/`out_error_len` receive string error, returns false.
 */
bool orkester_task_wait(orkester_task_t task,
                        void **out_value,
                        const char **out_error_ptr,
                        size_t *out_error_len);

/**
 * Block dispatching main-thread tasks while waiting. Consumes the handle.
 */
bool orkester_task_wait_main(orkester_task_t task,
                             void **out_value,
                             const char **out_error_ptr,
                             size_t *out_error_len);

/**
 * Clone a thread pool handle (cheap Arc clone).
 */
orkester_thread_pool_t orkester_thread_pool_clone(orkester_thread_pool_t pool);

/**
 * Create a thread pool with the given number of threads.
 */
orkester_thread_pool_t orkester_thread_pool_create(size_t num_threads);

void orkester_thread_pool_drop(orkester_thread_pool_t pool);

/**
 * Wrap a task with a timeout. Consumes the input task handle.
 */
orkester_task_t orkester_timeout(const struct orkester_t *system,
                                 orkester_task_t task,
                                 uint64_t millis);

/**
 * Destroy a value array and all remaining un-extracted values.
 */
void orkester_value_array_drop(void *array_payload);

/**
 * Extract the value pointer at `index` from a value array.
 * Transfers ownership to the caller. Each index should only be extracted once.
 */
void *orkester_value_array_get(void *array_payload, size_t index);

/**
 * Get the number of elements in a value array.
 */
size_t orkester_value_array_len(const void *array_payload);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
